services:
  web:
    build: ./app
    ports:
      - "5180:5180"
    volumes:
     - ./app:/app
     - /app/node_modules
    environment:
      NODE_ENV: development
      VITE_HOST: 0.0.0.0
    stdin_open: true
    tty: true
  
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
     - ./api:/app
     - /app/node_modules
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8002:8080
 
volumes:
  pgdata:

  