services:
  web:
    build: ./app
    ports:
      - "5180:5180"
    volumes:
     - ./app:/app
     - /app/node_modules
    environment:
      NODE_ENV: development
      VITE_HOST: 0.0.0.0
      VITE_API_URL: "http://localhost:3000/"
    stdin_open: true
    tty: true
  
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
     - ./api:/app
     - /app/node_modules
    environment:
      NODE_ENV: development
      JWT_SECRET: "test123"
      DATABASE_URL: "postgresql://postgres:example@db:5432/postgres"
    stdin_open: true
    tty: true
    command: npm run dev
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata_15:/var/lib/postgresql/data 
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
 
volumes:
  pgdata_15:

  